--- #YAML:1.0
name                    : Net-SSH-Perl
version                 : 2.00
abstract                : Perl client interface to SSH
author:              
  - David Robins <dbrobins@cpan.org>
  - Lance Kinley <lkinley@loyaltymethods.com>
license                 : perl
distribution_type       : module
dynamic_config          : 1

requires:     
  BSD::arc4random       : 1.50
  Convert::PEM          : 0.05
  Crypt::Curve25519     : 0.04
  Crypt::DES            : 0
  Crypt::DH             : 0.01
  Crypt::DSA            : 0.11
  Crypt::Ed25519        : 1.0
  Crypt::IDEA           : 0
  Crypt::OpenSSL::AES   : 0.03
  Digest::HMAC_MD5      : 0
  Digest::MD5           : 0
  Digest::SHA           : 4.0.0
  File::HomeDir         : 0
  IO::Socket            : 0
  Math::GMP             : 1.04
  Math::Pari            : 2.001804
  MIME::Base64          : 0
  Scalar::Util          : 0
  String::CRC32         : 1.2
build_requires:
  Test::More            : 0.61
recommends:
  Module::Signature     : 0.50
  Digest::BubbleBabble  : 0
  Crypt::RSA            : 0
  Term::ReadKey         : 0

resources:
  homepage              : http://search.cpan.org/dist/Net-SSH-Perl/
  license               : http://dev.perl.org/licenses/
  bugtracker            : http://rt.cpan.org/Public/Dist/Display.html?Name=Net-SSH-Perl
  MailingList           : https://lists.sourceforge.net/lists/listinfo/ssh-sftp-perl-users
  repository            : https://github.com/renormalist/Net-SSH-Perl

meta-spec:
  version               : 1.4
  url                   : http://module-build.sourceforge.net/META-spec-v1.4.html

generated_by            : emacs
